name: Waka Readme

on:
  schedule:
    # Runs at 18:30am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: Jackxul/NGLAB_Ticket_System@master
        with:
          WAKATIME_API_KEY: ${{ secrets.NGLAB_PJ1 }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
